runtime: php55
api_version: 1
threadsafe: true

handlers:



env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/hackathon-718718:asia-east1:travel718718;dbname=travel
  MYSQL_USER: root
  MYSQL_PASSWORD: root

beta_settings:
    cloud_sql_instances: "hackathon-718718:asia-east1:travel718718"