runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /countries
  script: www/getcountries.php
- url: /citybycountry
  script: www/getcitybycid.php
- url: /suppermoment
  script: www/api1.php
- url: /conn
  script: conn.php
- url: /images
  static_dir: images




env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/hackathon-718718:asia-east1:travel718718;dbname=travel;charset=utf8
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  enable_stackdriver_integration: true